### ISSUE TITLE
Enhancement: Grouping of paths

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [Yqnn/svg-path-editor#24]
I'd like to be able to translate sets of paths across to different areas. For example, here's a sample Path:
```
M 474.2 161.7 c -16.1 -46.6 -46.7 -87.1 -91.3 -109.6 c -51 -25.7 -111 -28.1 -166.4 -19.3 c -49.8 8 -102.3 26 -139.6 61.2 c -19.6 18.5 -34.7 40.9 -42.7 66.8 c -8 26 -10.4 53.1 -12.1 80.1 c -0.1 1.1 -0.4 2 -1 2.7 c 0 0.2 0.1 0.5 0.1 0.8 c 0 52.9 -1.1 108.3 30.1 153.9 c 25.3 37.1 64.5 61.5 107.2 73.7 c 88 25.2 194.2 9.6 264.9 -50.8 c 74.1 -63.3 80.9 -172.3 50.8 -259.5 z z z m -320.6 -91.2 h 2 c 0.4 0 0.9 0 1.3 0.1 c 10.1 0.6 17.7 4 23.9 12.8 c 6.8 9.6 12.7 19.9 17.8 30.6 c 2.4 -3.3 5.3 -6.3 8.2 -9.3 c 5 -5.1 8.9 -10 12.3 -16.4 c 3 -5.7 6.2 -11.5 11.5 -15.4 c 0.2 -0.5 0.3 -1 0.5 -1.4 c 1.4 -4.1 5.6 -3.8 8.2 -1.5 c 3.4 0 6.8 0.7 10.3 0.4 c 1.8 -0.2 3.4 0.6 4.4 1.8 c 0.7 0.1 1.4 0.2 2.1 0.3 c 4.4 0.7 5.4 5.9 3.1 9 c -13.9 18.8 -28.4 38 -45.7 54 c -0.1 20.2 -0.7 40.4 -0.2 60.6 c 0.7 0.8 1.2 1.9 1.2 3.4 v 0.3 c 0.2 0.7 0.2 1.4 0 2.1 v 0.6 c 0 2.8 -1.9 5.9 -5.1 5.9 h -1 c -0.6 0 -1.1 -0.1 -1.6 -0.2 c -1.7 0.2 -3.5 0.2 -5.4 0.2 c -3.4 0 -7.7 0.7 -10.5 -1.7 c -2.7 -2.3 -2.8 -5.7 -3.2 -9 c -0.8 -6.4 -0.6 -12.7 -0.4 -19.1 c 0.3 -9.4 -0.2 -18.6 -0.6 -27.9 c -0.2 -3.7 -0.5 -7.9 -0.3 -12.1 c -3.3 -6.5 -7.8 -12.3 -12.1 -18.1 c -3.3 -4.6 -6.5 -9.2 -10.1 -13.6 c -6.4 -7.8 -15.3 -17.5 -14.7 -28.3 m 4.1 -8.1 z z
```

And I'm trying to move the Y part to the center. You can see this operation is difficult as I need to move individual units. It would be nice to have a select logic to drag a box to select a bunch of paths and then group them and then translate the group across.

**Comment by Yqnn** [comment]
Hi,

That's something already doable using relative and absolute coordinate system cleverly.
It's not best-in-class UX, but it works for most use-cases.

The generic procedure is the following:
- convert the full path to absolute coordinates
- convert the command you want to move together to relative coordinates (they have to be consecutive)
- move the first command of the group

https://user-images.githubusercontent.com/588624/104196087-adb76d00-5423-11eb-8eb3-5a6fb98d586b.mp4


For your specific example if even simpler, just moving the first command of the Y is enough, because following commands are all part of the Y, and already defined as relative:

https://user-images.githubusercontent.com/588624/104196489-21597a00-5424-11eb-807c-75fb9633176d.mp4

**Comment by SaifurRahmanMohsin** [comment]
Oh wow, I didn't know that was possible @Yqnn. I guess you're right, the UI will be the main enchancement: where a user can use a select icon to make a selection covering a set of paths and then translate it across by dragging. Thanks for the video demo.

**Comment by AnweshGangula** [comment]
Wow, this is really good. I wasn't even aware that we can move an entire shape. And this shows how to move a shape within a shape.

This page is a hidden wiki. I only got to this because it was mentioned in an open issue. 
@Yqnn, I think you should enable the "Wiki" for this repo. That way interested folks and contributors can add things like this.
